In [2]:
pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4835 sha256=ff93a078016e372c4a697ddfb036d1ec0fffb375077701b3c1c564c95451f3fe
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
  Created wheel for absl-py: filename=absl_py-0.9.0-py3-none-any.whl size=121935 sha256=62ee1bd6882c05a83fcc34e238d0aaa9a39e21c02aefeca607afd0682645919e
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\cc\af\1a\498a24d0730ef484019e007bb9e8cef3ac00311a672c049a3e
Successfully built termcolor absl-py
Note: you may need to restart the kernel to use updated packages.


In [1]:
# Artificial Neural Network

# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.2.0'

# Part 1 - Data Preprocessing

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values#keeping only the columns that are relevant or have an impact on predicting the dependent variable(not keeping the dependent variable in it)
y = dataset.iloc[:, -1].values#in y we will store the dependent variable
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [3]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [4]:
# One Hot Encoding the "Geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling(It is very important to do feature scaling in NN)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Building the ANN

In [9]:
# Initializing the ANN
ann = tf.keras.models.Sequential()

In [ ]:
#normal input neurons would be the input columns i.e.,Surname,Geography,Gender and son on.

In [10]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))#using class dense and unit here specifies the no. of hidden neurons in the hidden layer(we randomly choose the no of neurons i.e., on experimental basis)
                                                        #here we have chosen the rectifier activation function(with code name'relu'by default activation function is None)

In [11]:
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [12]:
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))#no. of neurons in the output layer depends on the dimensions of the output
                                                            #here we need one 1 neuron to make the final prediction(if we were doing classification with a non-binary dependent variable having for eg 3 classes the in tat case we would actually need 3 dimensions to make prediction)
                                                            #for the output layer we need the sigmoid activation function(as it will not only tell us whether or not the customer will exit or not but also probability of each)
    

# Part 3 - Training the ANN


In [14]:
# Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])#whenever we are doing binary classification loss parameter must be'binary_crossentropy')
#for non-binary clasification loss paramter must be 'categorical_crossentropy'

In [15]:
# Training the ANN on the Training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)#using batch learing is more efficient when training ANN
                                                        #batch_size gives the no. of predictions we want to have in the batch to be compared to(by default also batch_size is 32)
                                                        #we use epochs to improve the accuracy over time

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6903 - accuracy: 0.6311
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4993 - accuracy: 0.7965
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4595 - accuracy: 0.7995
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4435 - accuracy: 0.8065
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4340 - accuracy: 0.8136
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4274 - accuracy: 0.8191
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4230 - accuracy: 0.8226
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4192 - accuracy: 0.8273
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4159 - accuracy: 0.8290
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4133 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3908 - accuracy: 0.8403
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3909 - accuracy: 0.8390
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.8386
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.8386
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3909 - accuracy: 0.8382
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3910 - accuracy: 0.8395
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3907 - accuracy: 0.8389
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3906 - accuracy: 0.8382
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3906 - accuracy: 0.8379
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3906 - accuracy: 

# Part 4 - Making the predictions and evaluating the model

In [16]:
# Predicting the result of a single observation

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)#we entered 1,0,0 and not france because the Geography variable was hot-encoded
                                                                                        #we used sc.transform because we training our network on scaled data(we will not use fit with test data to avoid data leakage)
                                                                                        #>0.5 will be used as a threshold that if the predicted prob is >0.5 then only it will be considered

[[False]]


In [18]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1543   52]
 [ 259  146]]


0.8445